version: '3.9'
services:
  db:
    container_name: db
    image: postgres:15.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  flask_app:
    container_name: flask_app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: postgresql://postgres:postgres@db:5432/mydb
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      -  .:/app/

volumes:
  pgdata: {}